import type { ScraperStrategy, TargetType } from "./types";

export type RecommendedScraperSource = {
  targetCode: string;
  name: string;
  url: string;
  targetType: TargetType;
  coverage: string;
  scrapeStrategy: ScraperStrategy;
  priority: number;
  maxPages: number;
  rateLimitMs: number;
  notes: string;
};

export const RECOMMENDED_SCRAPER_SOURCES: RecommendedScraperSource[] = [
  {
    targetCode: "sodre-santoro",
    name: "Sodre Santoro",
    url: "https://www.sodresantoro.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 59,
    maxPages: 10,
    rateLimitMs: 2500,
    notes: "Fonte recomendada para ampliar cobertura. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "hasta-publica",
    name: "Hasta Publica",
    url: "https://www.hastapublica.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 59,
    maxPages: 10,
    rateLimitMs: 2500,
    notes: "Fonte recomendada para ampliar cobertura. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "lance-ja",
    name: "Lance Ja",
    url: "https://www.lanceja.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 59,
    maxPages: 10,
    rateLimitMs: 2500,
    notes: "Fonte recomendada para ampliar cobertura. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "guariglia-leiloes",
    name: "Guariglia Leiloes",
    url: "https://www.guariglialeiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 59,
    maxPages: 10,
    rateLimitMs: 2500,
    notes: "Fonte recomendada para ampliar cobertura. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "nogari-leiloes",
    name: "Nogari Leiloes",
    url: "https://www.nogarileiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 59,
    maxPages: 10,
    rateLimitMs: 2500,
    notes: "Fonte recomendada para ampliar cobertura. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "kronberg-leiloes",
    name: "Kronberg Leiloes",
    url: "https://www.kronbergleiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 59,
    maxPages: 10,
    rateLimitMs: 2500,
    notes: "Fonte recomendada para ampliar cobertura. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "frazao-leiloes",
    name: "Frazao Leiloes",
    url: "https://www.frazaoleiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 59,
    maxPages: 10,
    rateLimitMs: 2500,
    notes: "Fonte recomendada para ampliar cobertura. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "leiloes-judiciais",
    name: "Leiloes Judiciais",
    url: "https://www.leiloesjudiciais.com.br/",
    targetType: "aggregator",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 63,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica concorrente/agregadora com mapa e categorias de imoveis. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "franco-leiloes",
    name: "Franco Leiloes",
    url: "https://www.francoleiloes.com.br/busca/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 63,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica especializada em leiloes judiciais e extrajudiciais. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "alvaro-leiloes",
    name: "Alvaro Leiloes",
    url: "https://www.alvaroleiloes.com.br/leilao/index/imoveis",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 61,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica com filtro direto para imoveis. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "alfa-leiloes",
    name: "Alfa Leiloes",
    url: "https://alfaleiloes.com/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 61,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica especialista em imoveis. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "grupo-lance",
    name: "Grupo Lance",
    url: "https://www.grupolance.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 60,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica com secao de imoveis em leiloes judiciais e extrajudiciais. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "rj-leiloes",
    name: "RJ Leiloes",
    url: "https://www.rjleiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 58,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica com leiloes de imoveis e bens judiciais. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "portella-leiloes",
    name: "Portella Leiloes",
    url: "https://portellaleiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 58,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica com categorias de imoveis, casas, apartamentos, terrenos e rural. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "mapa-do-leilao",
    name: "Mapa do Leilao",
    url: "https://mapadoleilao.com.br/",
    targetType: "aggregator",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 58,
    maxPages: 10,
    rateLimitMs: 3500,
    notes: "Agregador publico de leiloes e vendas diretas verificados. Verificado por HTTP antes do cadastro.",
  },
  {
    targetCode: "hd-leiloes",
    name: "HD Leiloes",
    url: "https://www.hdleiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 57,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica com secoes de imoveis e mapa de imoveis. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "legis-leiloes",
    name: "Legis Leiloes",
    url: "https://www.legisleiloes.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 57,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica de leiloes judiciais e extrajudiciais. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "d1lance",
    name: "D1Lance",
    url: "https://d1lance.com.br/",
    targetType: "auctioneer",
    coverage: "nacional",
    scrapeStrategy: "fetch",
    priority: 57,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica com imoveis e veiculos; filtro de qualidade separa bens nao imobiliarios. Verificada por HTTP antes do cadastro.",
  },
  {
    targetCode: "edgar-carvalho",
    name: "Edgar Carvalho Leiloeiro",
    url: "https://www.edgarcarvalholeiloeiro.com.br/",
    targetType: "auctioneer",
    coverage: "regional",
    scrapeStrategy: "fetch",
    priority: 56,
    maxPages: 10,
    rateLimitMs: 3000,
    notes: "Fonte publica regional com mapa de imoveis. Verificada por HTTP antes do cadastro.",
  },
];
