/* eslint-disable @typescript-eslint/no-require-imports -- Offline PostgreSQL integration. */
const { PGlite } = require('@electric-sql/pglite');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {loadSource}=require('./helpers/load-source.cjs');
async function main(){
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table whatsapp_leads(id uuid primary key,phone text,name text,opt_out boolean default false);
 create table whatsapp_conversations(id uuid primary key,lead_id uuid);
 create table whatsapp_conversation_messages(id uuid primary key,lead_id uuid,conversation_id uuid,direction text,author_type text,payload jsonb,text text,created_at timestamptz default now());
 create table whatsapp_lead_files(id uuid primary key default gen_random_uuid(),lead_id uuid,conversation_id uuid,message_id uuid,source text,file_url text,mime_type text,metadata jsonb,created_at timestamptz default now());`);
 await db.exec(fs.readFileSync('supabase/migrations/20260914220000_betel_native_journey.sql','utf8'));
 const recipient=randomUUID(),actor=randomUUID(),visitor=randomUUID(),otherVisitor=randomUUID(),link=randomUUID(),group=randomUUID(),event=randomUUID(),claim=randomUUID(),message=randomUUID();
 await db.query('insert into whatsapp_leads(id,phone) values($1,$2),($3,$4)',[recipient,'5511999000001',actor,'5511999000002']);
 await db.query("insert into betel_visitors(id,token_hash,expires_at) values($1,'fixture',now()+interval '30 days'),($2,'other',now()+interval '30 days')",[visitor,otherVisitor]);
 await db.query("insert into betel_tracked_links(id,dedup_key,target_url,label,source,intended_lead_id,recipient_kind,context) values($1,'direct','https://example.org/property','Aluguel 1','whatsapp',$2,'direct','{\"campaignId\":\"fixture\"}'),($3,'group','https://chat.whatsapp.com/fixture','Convite','whatsapp',null,'group','{}')",[link,recipient,group]);
 const click=(l,e,v=null)=>db.query('select record_betel_link_click($1,$2,$3,90) id',[l,e,v]);
 const first=(await click(link,event,visitor)).rows[0].id;
 assert.equal((await click(link,event,visitor)).rows[0].id,first,'retry same event returns same file');
 await click(link,randomUUID(),visitor);
 assert.equal((await db.query('select count(*)::int n from whatsapp_lead_files')).rows[0].n,2,'two genuine clicks retained');
 await assert.rejects(()=>click(group,event,visitor),/EVENT_SCOPE_MISMATCH/);
 await click(group,randomUUID());
 const anon=(await db.query('select * from whatsapp_lead_files where id=$1',[first])).rows[0];
 assert.equal(anon.lead_id,null);assert.equal(anon.intended_lead_id,recipient);assert.equal(anon.metadata.actorConfirmed,false);
 assert.equal((await db.query('select * from betel_recent_journey($1,40)',[[recipient]])).rows.length,2,'recipient timeline includes anonymous events without claiming actor');
 const code='a'.repeat(32);
 await db.query('insert into betel_visitor_claims(id,visitor_id,code) values($1,$2,$3)',[claim,visitor,code]);
 const confirm=(v=visitor)=>db.query('select confirm_betel_visitor($1,$2) ok',[v,claim]);
 assert.equal((await confirm()).rows[0].ok,false,'unverified phone never binds');
 const inbound=async(id,reliable,chatId='5511999000002@s.whatsapp.net')=>db.query('insert into whatsapp_conversation_messages(id,lead_id,direction,author_type,text,payload) values($1,$2,$3,$4,$5,$6)',[id,actor,'inbound','lead',`Meu codigo BETEL-${code}`,JSON.stringify({betel_identity:{identityReliable:reliable,chatId}})]);
 await inbound(randomUUID(),false); assert.equal((await confirm()).rows[0].ok,false,'unreliable sender excluded');
 await inbound(randomUUID(),true,'120000@g.us'); assert.equal((await confirm()).rows[0].ok,false,'group cannot claim identity');
 await inbound(message,true);
 assert.equal((await confirm(otherVisitor)).rows[0].ok,false,'other browser cannot claim');
 assert.equal((await db.query('select lead_id from betel_visitors where id=$1',[visitor])).rows[0].lead_id,null,'inbound alone does not identify browser');
 assert.equal((await confirm()).rows[0].ok,true);assert.equal((await confirm()).rows[0].ok,true,'confirm replay safe');
 const bound=(await db.query('select * from whatsapp_lead_files where id=$1',[first])).rows[0];
 assert.equal(bound.lead_id,actor);assert.equal(bound.intended_lead_id,recipient);assert.equal(bound.metadata.actorConfirmed,true);
 assert.equal((await db.query('select * from betel_recent_journey($1,40)',[[actor]])).rows.length,2,'confirmed actor receives original events');
 const timeline=loadSource('src/lib/whatsapp/journey-timeline.ts');
 assert.match(timeline.journeyTimelineMessage(bound,recipient).text,/outro contato confirmado/);
 assert.match(timeline.journeyTimelineMessage(bound,actor).text,/Contato confirmado/);
 assert.equal((await db.query("select lead_id from whatsapp_lead_files where metadata->>'recipientKind'='group'")).rows[0].lead_id,null,'anonymous group remains anonymous');
 await db.query("update whatsapp_lead_files set expires_at=now()-interval '1 second' where visitor_id=$1",[visitor]);
 await db.query("update betel_visitors set expires_at=now()-interval '1 second' where id=$1",[visitor]);
 await db.query('select prune_betel_journey()');
 assert.equal((await db.query('select count(*)::int n from whatsapp_lead_files')).rows[0].n,1,'expiry deletes only expired journey files');
 assert.equal((await db.query('select count(*)::int n from whatsapp_leads')).rows[0].n,2,'no contacts duplicated or deleted');
 await db.exec('set role anon');
 await assert.rejects(()=>click(link,randomUUID()),/permission denied/);
 await assert.rejects(()=>db.query('select * from betel_visitors'),/permission denied/);
 await db.close();
 console.log('PASS PostgreSQL: native click -> existing lead file -> timeline; duplicate retries, distinct clicks, group/forward attribution, two-step verified identity, retention and privilege isolation. No network or production rows.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
