-- Add a controlled first batch of public competitor/aggregator sources.
insert into public.scraper_targets (
  target_code,
  name,
  url,
  target_type,
  coverage,
  scrape_strategy,
  selectors,
  schedule_cron,
  enabled,
  priority,
  max_pages,
  rate_limit_ms,
  notes
) values
  (
    'leiloes-judiciais',
    'Leiloes Judiciais',
    'https://www.leiloesjudiciais.com.br/',
    'aggregator',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    63,
    10,
    3000,
    'Fonte publica concorrente/agregadora com mapa e categorias de imoveis. Verificada por HTTP antes do cadastro.'
  ),
  (
    'franco-leiloes',
    'Franco Leiloes',
    'https://www.francoleiloes.com.br/busca/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    63,
    10,
    3000,
    'Fonte publica especializada em leiloes judiciais e extrajudiciais. Verificada por HTTP antes do cadastro.'
  ),
  (
    'alvaro-leiloes',
    'Alvaro Leiloes',
    'https://www.alvaroleiloes.com.br/leilao/index/imoveis',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    61,
    10,
    3000,
    'Fonte publica com filtro direto para imoveis. Verificada por HTTP antes do cadastro.'
  ),
  (
    'alfa-leiloes',
    'Alfa Leiloes',
    'https://alfaleiloes.com/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    61,
    10,
    3000,
    'Fonte publica especialista em imoveis. Verificada por HTTP antes do cadastro.'
  ),
  (
    'grupo-lance',
    'Grupo Lance',
    'https://www.grupolance.com.br/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    60,
    10,
    3000,
    'Fonte publica com secao de imoveis em leiloes judiciais e extrajudiciais. Verificada por HTTP antes do cadastro.'
  ),
  (
    'rj-leiloes',
    'RJ Leiloes',
    'https://www.rjleiloes.com.br/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    58,
    10,
    3000,
    'Fonte publica com leiloes de imoveis e bens judiciais. Verificada por HTTP antes do cadastro.'
  ),
  (
    'portella-leiloes',
    'Portella Leiloes',
    'https://portellaleiloes.com.br/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    58,
    10,
    3000,
    'Fonte publica com categorias de imoveis, casas, apartamentos, terrenos e rural. Verificada por HTTP antes do cadastro.'
  ),
  (
    'mapa-do-leilao',
    'Mapa do Leilao',
    'https://mapadoleilao.com.br/',
    'aggregator',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    58,
    10,
    3500,
    'Agregador publico de leiloes e vendas diretas verificados. Verificado por HTTP antes do cadastro.'
  ),
  (
    'hd-leiloes',
    'HD Leiloes',
    'https://www.hdleiloes.com.br/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    57,
    10,
    3000,
    'Fonte publica com secoes de imoveis e mapa de imoveis. Verificada por HTTP antes do cadastro.'
  ),
  (
    'legis-leiloes',
    'Legis Leiloes',
    'https://www.legisleiloes.com.br/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    57,
    10,
    3000,
    'Fonte publica de leiloes judiciais e extrajudiciais. Verificada por HTTP antes do cadastro.'
  ),
  (
    'd1lance',
    'D1Lance',
    'https://d1lance.com.br/',
    'auctioneer',
    'nacional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    57,
    10,
    3000,
    'Fonte publica com imoveis e veiculos; filtro de qualidade separa bens nao imobiliarios. Verificada por HTTP antes do cadastro.'
  ),
  (
    'edgar-carvalho',
    'Edgar Carvalho Leiloeiro',
    'https://www.edgarcarvalholeiloeiro.com.br/',
    'auctioneer',
    'regional',
    'fetch',
    '{}'::jsonb,
    '0 */6 * * *',
    true,
    56,
    10,
    3000,
    'Fonte publica regional com mapa de imoveis. Verificada por HTTP antes do cadastro.'
  )
on conflict (target_code) do update set
  name = excluded.name,
  url = excluded.url,
  target_type = excluded.target_type,
  coverage = excluded.coverage,
  scrape_strategy = excluded.scrape_strategy,
  priority = excluded.priority,
  max_pages = excluded.max_pages,
  rate_limit_ms = excluded.rate_limit_ms,
  notes = excluded.notes,
  enabled = true,
  consecutive_errors = 0,
  updated_at = now();
